import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => { try { const t = localStorage.getItem('theme') || 'light'; document.documentElement.setAttribute('data-theme', t); const savedLoc = localStorage.getItem('locale'); const nav = navigator.language || 'en'; const loc = savedLoc === 'ko' || savedLoc === 'en' ? savedLoc : (nav.toLowerCase().startsWith('ko') ? 'ko' : 'en'); document.documentElement.setAttribute('lang', loc); document.documentElement.setAttribute('data-locale', loc); } catch (_) {} })();`,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
